server:
  port: 8084

spring:
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/game_db
    username: postgres
    password: 1234
  cloud:
    function:
      definition: gameCreatedBinding
    stream:
      default-binder: kafka_default # Set kafka_default as the default binder
      bindings:
        gameCreatedBinding-in-0:
          destination: event.game-created
          binder: kafka_default  # Updated binder to kafka_default
          useNativeDecoding: true
        gameCreatedBinding-out-0:
          destination: event.game-eligible
          binder: kafka_default  # Updated binder to kafka_default
          useNativeDecoding: true
        binding:
          destination: event.file-started
          binder: kafka_default  # Use kafka_default as the binder for this binding
          useNativeDecoding: true
      binders:
        kafka_default: # Add kafka_default binder
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    default:
                      consumer:
                        configuration:
                          session.timeout.ms: 60000
                          max.poll.records: 10
                      producer:
                        compressionType: gzip
                        configuration:
                          max.request.size: 322232
                    binder:
                      autoAddPartitions: true
                      autoCreateTopics: true
                      requiredAcks: -1
                      minPartitionCount: 3
                      replicationFactor: 1
                      serdeError: logAndContinue
                      brokers: localhost:9092  # Ensure your Kafka broker is running at this address
