server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kafka
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    function:
      definition:
    stream:
      default-binder: kafka-default
      bindings:
        gameBinding-out-0:
          destination: event.game-created
          binder: kafka-default
          useNativeDecoding: true